### ISSUE TITLE
Logo For Qurany App

### ISSUE THREAD

**Issue by zularizal** [MahmoudMabrok/QuranyApp#1]
Assalammu'alaikum @MahmoudMabrok  , I like the project about the Qur'an. I want to contribute by creating a new logo for this project. What do you think?

**Comment by MahmoudMabrok** [comment]
it's a good idea you can go on.
thank you for your contribution

**Comment by zularizal** [comment]
Hi @MahmoudMabrok , here are some logos for your project. What do you think? Which one do you like?

If there is something you want to change, let me know.
![bitmap](https://user-images.githubusercontent.com/38547278/56033648-2cfba680-5d4f-11e9-9619-a8ff585134f5.png)

**Comment by MahmoudMabrok** [comment]
First thanks for your effort.
first is good.
could you make another copy of it using the same colors of the third one

**Comment by zularizal** [comment]
Okay @MahmoudMabrok , Left or right brother?

![bitmap](https://user-images.githubusercontent.com/38547278/56078230-d6a26c80-5e0f-11e9-9ee9-973ed71ef061.png)

**Comment by MahmoudMabrok** [comment]
right bro

**Comment by zularizal** [comment]
Okay, I will make pr

**Comment by MahmoudMabrok** [comment]
could you make latest one plus first one with original color

**Comment by zularizal** [comment]
Hi @MahmoudMabrok  , I have sent pull request. I chose the last icon you chose. #5 

And also I have uploaded the first alternative icon on the drive.
Check this link.
https://drive.google.com/open?id=1DRQFIPrrdkAh9T6-FCJMEo3YCMRTirMh

**Comment by MahmoudMabrok** [comment]
Thanks @zularizal

**Comment by MahmoudMabrok** [comment]
please could u make one log for play with arabic name  القران الكريم 
 need only one image for google play 

I greateful for u.

**Comment by zularizal** [comment]
Of course, I will make it.
Give me time to make it.

**Comment by zularizal** [comment]
Do you mean like this? @MahmoudMabrok 

![23](https://user-images.githubusercontent.com/38547278/56089790-86381700-5ec2-11e9-9de6-753d0eea3e93.png)

**Comment by MahmoudMabrok** [comment]
thanks bro.

**Comment by zularizal** [comment]
Wait, I will upload it to drive.

**Comment by zularizal** [comment]
Okay @MahmoudMabrok , I have uploaded it. Check this.
https://drive.google.com/drive/u/1/folders/1DRQFIPrrdkAh9T6-FCJMEo3YCMRTirMh

**Comment by MahmoudMabrok** [comment]
Thanks
