### ISSUE TITLE
[QuranyApp][v1.8.61] The app crashes if I click on sound option

### ISSUE THREAD

**Issue by 44asad** [MahmoudMabrok/QuranyApp#11]
### Expected behavior
The application should not crash when I click on sound option.

### Actual behavior:
The application is crash when I click on sound option.

### How to reproduce:
* Download the app and open it
* click Naw sound option
* see bug
### Recording Of The Bug:

https://youtu.be/86YBOEZU3fI

### Test Environment:
Device:samsung J5
OS: Android 6.0.1
Version: Esteem mobile v1.8.61

### logcat:
<pre><code>05-15 07:16:14.924 22119 22119 E AndroidRuntime: FATAL EXCEPTION: main
05-15 07:16:14.924 22119 22119 E AndroidRuntime: Process: education.mahmoud.quranyapp, PID: 22119
05-15 07:16:14.924 22119 22119 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String education.mahmoud.quranyapp.data_layer.local.room.g.f' on a null object reference
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at education.mahmoud.quranyapp.feature.listening_activity.ListenFragment$1.onItemSelected(Unknown Source)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.widget.AdapterView.fireOnSelected(AdapterView.java:1166)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1155)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.widget.AdapterView.access$300(AdapterView.java:60)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1122)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-15 07:16:14.924 22119 22119 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by MahmoudMabrok** [comment]
try the latest version in repository V1.9

**Comment by 44asad** [comment]
ok sir
