### ISSUE TITLE
[QuranyApp][v1.8.61] The app crashes if I click on "Go" option

### ISSUE THREAD

**Issue by 44asad** [MahmoudMabrok/QuranyApp#12]
### Expected behavior
The application should not crash when I click on jump "Go" option

### Actual behavior:
The application is crash when I click on "Go" option.

### How to reproduce:
* Download the app and open it
* click Naw menu icon
* Then click naw Jump option &
* "Go" 
* see bug
### Recording Of The Bug:

https://youtu.be/neq7I55Hm20

### Test Environment:
Device:samsung J5
OS: Android 6.0.1
Version: Esteem mobile v1.8.61

### logcat:
<pre><code>05-15 07:16:00.124 21094 21094 E AndroidRuntime: FATAL EXCEPTION: main
05-15 07:16:00.124 21094 21094 E AndroidRuntime: Process: education.mahmoud.quranyapp, PID: 21094
05-15 07:16:00.124 21094 21094 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String education.mahmoud.quranyapp.data_layer.local.room.g.f' on a null object reference
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at education.mahmoud.quranyapp.feature.listening_activity.ListenFragment$1.onItemSelected(Unknown Source)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.widget.AdapterView.fireOnSelected(AdapterView.java:1166)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1155)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.widget.AdapterView.access$300(AdapterView.java:60)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1122)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-15 07:16:00.124 21094 21094 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by MahmoudMabrok** [comment]
Thanks for the bug report.
I have updated app, could you try it again?

link is in repo
https://github.com/MahmoudMabrok/QuranyApp/tree/master/apk

**Comment by 44asad** [comment]
ok sir

**Comment by MahmoudMabrok** [comment]
@44asad  is it solved?

**Comment by MahmoudMabrok** [comment]
@44asad please reply or you should close the issue?
