### ISSUE TITLE
(BUG) APPLICATION crashes when I click on GO BY JUZ

### ISSUE THREAD

**Issue by saraji-ali** [MahmoudMabrok/QuranyApp#15]
# Project Information

* Repository: https://github.com/MahmoudMabrok/QuranyApp
* Project Name: QuranyApp

# Expected behavior

The application should not be crashed when I click on GO BY JUZ Rather, the option in GO BY JUZ should appear

# Actual behavior
After going to the JUMP option, the application crashes when I click on GO BY JUZ.# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=education.mahmoud.quranyapp)the app and open it
2-Click on three vertical dots
3- click on the Jump
4- click on GO BY JUZ
5- see bug 

* Browser/App version:  Current Version 1.8.61
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190518_165538](https://user-images.githubusercontent.com/50115498/57969389-3ddda000-792b-11e9-964f-5939f41387e4.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(22838): FATAL EXCEPTION: main

E/AndroidRuntime(22838): Process: education.mahmoud.quranyapp, PID: 22838

E/AndroidRuntime(22838): java.lang.NumberFormatException: Invalid int: ""

E/AndroidRuntime(22838): 	at java.lang.Integer.invalidInt(Integer.java:138)

E/AndroidRuntime(22838): 	at java.lang.Integer.parseInt(Integer.java:358)

E/AndroidRuntime(22838): 	at java.lang.Integer.parseInt(Integer.java:334)

E/AndroidRuntime(22838): 	at education.mahmoud.quranyapp.feature.show_sura_list.GoToSurah.onViewClicked(Unknown Source)

E/AndroidRuntime(22838): 	at education.mahmoud.quranyapp.feature.show_sura_list.GoToSurah_ViewBinding$1.a(Unknown Source)

E/AndroidRuntime(22838): 	at butterknife.a.a.onClick(Unknown Source)

E/AndroidRuntime(22838): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(22838): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(22838): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(22838): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(22838): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(22838): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(22838): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(22838): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(22838): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(22838): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by MahmoudMabrok** [comment]
I am sorry for this bug, it has been solved but the latest version is not available in Play Store (as it takes time for review )


latest version

https://github.com/MahmoudMabrok/QuranyApp/tree/master/apk


I look forward to listening from you after try this latest version

**Comment by saraji-ali** [comment]
thanks your sir bug has been solved thanks you
