### ISSUE TITLE
[QuranyApp][v1.9.0] The app crashes if I click on man icon

### ISSUE THREAD

**Issue by 44asad** [MahmoudMabrok/QuranyApp#16]
### Expected behavior
The application should not crash when I click man icon.

### Actual behavior:
The application is crash when I click man icon option.

### How to reproduce:
* Download the app and open it
* click Naw man icon option
* see bug
### Recording Of The Bug:

https://youtu.be/p8B_hs7nltM

### Test Environment:
* Device:samsung J5
* OS: Android 6.0.1
* Version: v1.9.0
### Logcat:
<pre><code>05-18 02:36:10.416  8834  8834 E AndroidRuntime: FATAL EXCEPTION: main
05-18 02:36:10.416  8834  8834 E AndroidRuntime: Process: com.bitcoin.wallet.btc, PID: 8834
05-18 02:36:10.416  8834  8834 E AndroidRuntime: android.content.res.Resources$NotFoundException: Resource ID #0x7f0800da
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.content.res.Resources.getValue(Resources.java:2558)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.content.res.Resources.getDrawable(Resources.java:2001)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.content.res.Resources.getDrawable(Resources.java:1987)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.content.Context.getDrawable(Context.java:464)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.preference.Preference.onBindViewHolder(Preference.java:597)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.preference.SwitchPreference.onBindViewHolder(SwitchPreference.java:145)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:381)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:45)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-18 02:36:10.416  8834  8834 E AndroidRuntime:   at android.widget.LinearLayout.onLayout(LinearLayo</code></pre>

**Comment by 44asad** [comment]
@MahmoudMabrok pleased  check it!

**Comment by MahmoudMabrok** [comment]
I am so sorry, I have been tried to get the cause of the problem but I can not.
It seems it a problem with Your Android Version.

**Comment by 44asad** [comment]
ok!

**Comment by MahmoudMabrok** [comment]
issue solved or not ?

**Comment by 44asad** [comment]
solved!  thanks you
