### ISSUE TITLE
[QuranyApp][v1.9.0] The app crashes if I click on "Score "option

### ISSUE THREAD

**Issue by 44asad** [MahmoudMabrok/QuranyApp#18]
### Expected behavior
I expected that the app would not crash when I click on Score option .I believe the users should be able to press the Score during that encryption process.

### Actual behavior:
The application is crash when I click "Score" option.

### How to reproduce:
* Download the app and open it
* click Naw menu icon
* then click  score 
* and click to 2 setp back batton
* see bug
### Recording Of The Bug:

https://youtu.be/Mzzgq0AwZrk

### Test Environment:
* Device:samsung J5
* OS: Android 6.0.1
* Version: v1.9.0
### Logcat:
<pre><code>05-18 03:02:34.515 12318 12318 E AndroidRuntime: FATAL EXCEPTION: main
05-18 03:02:34.515 12318 12318 E AndroidRuntime: Process: education.mahmoud.quranyapp, PID: 12318
05-18 03:02:34.515 12318 12318 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.ybq.android.spinkit.SpinKitView.setVisibility(int)' on a null object reference
05-18 03:02:34.515 12318 12318 E AndroidRuntime:   at education.mahmoud.quranyapp.feature.show_sura_list.SuraListFragment$1.handleMessage(Unknown Source)
05-18 03:02:34.515 12318 12318 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:102)
05-18 03:02:34.515 12318 12318 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-18 03:02:34.515 12318 12318 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-18 03:02:34.515 12318 12318 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-18 03:02:34.515 12318 12318 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-18 03:02:34.515 12318 12318 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by 44asad** [comment]
@MahmoudMabrok,pleased  chack is my issues

**Comment by MahmoudMabrok** [comment]
I am sorry I can not reproduce your bug.

**Comment by 44asad** [comment]
@MahmoudMabrok
last version  same problems .

**Comment by 44asad** [comment]
today downloads  last version 1.9

**Comment by MahmoudMabrok** [comment]
It seems a problem with the os of your phone 
as I test in different devices and It works correctly.

V1.9 is to overcome this problem, but with you, I  do not know why it's not working

**Comment by 44asad** [comment]
ok sir thanks  you

**Comment by MahmoudMabrok** [comment]
why close issue?
is it solved?

**Comment by 44asad** [comment]
yes!thanks you

**Comment by MahmoudMabrok** [comment]
do you any feature?
