### ISSUE TITLE
(BUG) (QuranyApp version 1.8.96 ) The application crashes when I click on the read button

### ISSUE THREAD

**Issue by saraji-ali** [MahmoudMabrok/QuranyApp#19]
# Project Information

* Repository: https://github.com/MahmoudMabrok/QuranyApp
* Project Name: QuranyApp

# Expected behavior

When I click on the read button, the application should not crash All options in the read button should appear

# Actual behavior
After opening the appl
ication's Latest version, the application crashes when I click on the read button.

# How to reproduce

1-[Download ](https://github.com/MahmoudMabrok/QuranyApp/tree/master/apk)the app and open it
2- Click the read button at the bottom left side
3- see bug

* Browser/App version: 1.8.96
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190519_014103](https://user-images.githubusercontent.com/50115498/57974847-a5b7d900-7973-11e9-8a5e-a9e890d986ca.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(14733): FATAL EXCEPTION: main

E/AndroidRuntime(14733): Process: education.mahmoud.quranyapp, PID: 14733

E/AndroidRuntime(14733): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.ybq.android.spinkit.SpinKitView.setVisibility(int)' on a null object reference

E/AndroidRuntime(14733): 	at education.mahmoud.quranyapp.feature.show_sura_list.SuraListFragment$1.handleMessage(Unknown Source)

E/AndroidRuntime(14733): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(14733): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(14733): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(14733): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(14733): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(14733): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(14733): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by MahmoudMabrok** [comment]
try the latest version in repository V1.9

**Comment by saraji-ali** [comment]
the bug has been fixed in the latest version
