### ISSUE TITLE
[ Quranapp application v1.8.96 ] When I Exit from the application, the application crashes

### ISSUE THREAD

**Issue by XAMIR555** [MahmoudMabrok/QuranyApp#20]
#### Project Information
* Repository---------------:[Here](https://github.com/MahmoudMabrok/QuranyApp)
* Project Name-----------: [QuranyApp](https://github.com/MahmoudMabrok/QuranyApp/tree/master/apk)
* Publisher-----------------:  [Mahmoud Mabrok Fouad](https://github.com/MahmoudMabrok)
* My GitHub account---:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When any user exits the application the application  should not be crash during the exit

#### Actual behavior

After opening the application's Latest version When I Exit from the application, the application crashes

#### How to reproduce
* [Download ](https://github.com/MahmoudMabrok/QuranyApp/tree/master/apk)latest version 
* Open the application
* Click on the exit button to close the application
* Note the Bug
* Browser/App version-: v1.8.96
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190519_015914.gif](https://ipfs.busy.org/ipfs/QmaynVtfCthBNnaNg3d9bmGtZ4hsctM7wxkgKiGjCsSA9N)

# Logcat

<pre><code>05-18 17:01:07.585 17026 17026 E AndroidRuntime: FATAL EXCEPTION: main
05-18 17:01:07.585 17026 17026 E AndroidRuntime: Process: education.mahmoud.quranyapp, PID: 17026
05-18 17:01:07.585 17026 17026 E AndroidRuntime: java.lang.NumberFormatException: For input string: ""
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:627)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:650)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at education.mahmoud.quranyapp.feature.show_sura_list.GoToSurah.onJuz(Unknown Source:10)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at education.mahmoud.quranyapp.feature.show_sura_list.GoToSurah_ViewBinding$2.a(Unknown Source:2)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at butterknife.a.a.onClick(Unknown Source:12)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27788)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-18 17:01:07.585 17026 17026 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

</code></pre>

**Comment by MahmoudMabrok** [comment]
try the latest version in repository V1.9

**Comment by XAMIR555** [comment]
thanks you sir bug has been solved now
