### ISSUE TITLE
(BUG) (QuranyApp version 1.8.96 ) The application crashes when I click on 2nd man icon

### ISSUE THREAD

**Issue by saraji-ali** [MahmoudMabrok/QuranyApp#21]
# Project Information

* Repository: https://github.com/MahmoudMabrok/QuranyApp
* Project Name: QuranyApp

# Expected behavior
When I click on 2nd man icon, the application should not crash, all of the options in the 2nd man icon should appear.

# Actual behavior

The application crashes when I click on 2nd man icon

# How to reproduce

1-[Download ](https://github.com/MahmoudMabrok/QuranyApp/tree/master/apk)the app and open it
2- Click on 2nd man icon
3- see bug 

* Browser/App version: version 1.8.96
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190519_025618](https://user-images.githubusercontent.com/50115498/57975521-83c45380-797f-11e9-9297-ab7a2c13423b.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime( 7622): FATAL EXCEPTION: main

E/AndroidRuntime( 7622): Process: education.mahmoud.quranyapp, PID: 7622

E/AndroidRuntime( 7622): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.ybq.android.spinkit.SpinKitView.setVisibility(int)' on a null object reference

E/AndroidRuntime( 7622): 	at education.mahmoud.quranyapp.feature.show_sura_list.SuraListFragment$1.handleMessage(Unknown Source)

E/AndroidRuntime( 7622): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 7622): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 7622): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 7622): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 7622): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 7622): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 7622): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by MahmoudMabrok** [comment]
try the latest version in repository V1.9

**Comment by saraji-ali** [comment]
the bug has been fixed in latest version
