### ISSUE TITLE
(BUG) (QuranyApp version 1.9.0 )  Rate It button is not working properly

### ISSUE THREAD

**Issue by saraji-ali** [MahmoudMabrok/QuranyApp#23]
# Project Information

* Repository: https://github.com/MahmoudMabrok/QuranyApp
* Project Name: QuranyApp

# Expected behavior

When I click on the Rate-it option, the application should open on google play store or open on f -droid where I can rate this application.

# Actual behavior

When I click on the Rate -it option, there is an error as it is written (no app such found)

# How to reproduce

1-[Download ](https://apt.izzysoft.de/fdroid/index/apk/education.mahmoud.quranyapp)the app and open it
2-After checking all the options, turn off the application
3- Then open the application again
4-Click on the rate it option
5- see bug

* Browser/App version:  version 1.9.0
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190520_021049](https://user-images.githubusercontent.com/50115498/57988310-796a8e00-7a41-11e9-9957-b87301615a16.gif)

# My Github Account
https://github.com/facebook-786

**Comment by MahmoudMabrok** [comment]
I am sorry I think Rate will not work only if you download the app from google play.
Are you have google play installed on your device?

**Comment by saraji-ali** [comment]
yeah i download from  google play

**Comment by MahmoudMabrok** [comment]
It seems a problem with AppRate Services. Thanks for your report.

**Comment by saraji-ali** [comment]
welcome sir
