### ISSUE TITLE
App got crashed when rotating in landscape mode while listening quran.

### ISSUE THREAD

**Issue by Xeeshuu** [MahmoudMabrok/QuranyApp#24]
**Describe the bug**
When I opened the app and then tried to listen some quran aya's. Then i goes to listen section and started listening some aya's. Suddenly i turned my phone to landscape mode the audio got stopped and app has been got crashed. It brings me to my home screen.

**To Reproduce**
1. Open the app.
2. Click on the **Listen** option on the bottom of the app.
3. The enter **start aya** and **end aya**.
4. Then click on **listen**.
5. The audio will start streaming and then rotate your device.
6. The audio will stop and it will bring you to home screen.

**Expected behavior**
The app must be able to stream audio in any form while in landscape or portrait.
It should stream audio during rotating device.

**Screenshots**
![20190520_125243](https://user-images.githubusercontent.com/37048348/58004515-06c0e780-7b01-11e9-9e0c-dffa664792ec.gif)

**Smartphone:**
 - Device: [RedMi S2/Y2]
 - OS: [8.1.0]
 - Version [1.9.0]

**Comment by MahmoudMabrok** [comment]
I made a  solution, but it prevents you from landscape mode.

**Comment by MahmoudMabrok** [comment]
issue is solved.
