### ISSUE TITLE
Add Setting screen ?  

### ISSUE THREAD

**Issue by MahmoudMabrok** [MahmoudMabrok/QuranyApp#3]
Setting screen change layout color, style, change the language of the app.

**Comment by Abdulkadir98** [comment]
Hello, can I work on this? also, can I do this in Kotlin

**Comment by MahmoudMabrok** [comment]
I add A one but you can Improve it with adding UI and features 
I prefer java.

**Comment by Abdulkadir98** [comment]
Hi, I prefer Kotlin in all of my projects. If you change your mind let me know, thanks anyway :)

**Comment by MahmoudMabrok** [comment]
I also prefer Kotlin but when the code has both it takes a long time for debugging.

you can do it in Kotlin and I try to solve Issues with kotlin

**Comment by MahmoudMabrok** [comment]
Are you started to make it? @Abdulkadir98

**Comment by Abdulkadir98** [comment]
I am not able to run the app, some resource files are missing for me. I have updated my forked copy with the latest. Am I doing something wrong?
![Screenshot (8)](https://user-images.githubusercontent.com/22325142/56714491-95d11e80-6752-11e9-8132-ee0d972e41bd.png)
@MahmoudMabrok

**Comment by MahmoudMabrok** [comment]
these XML files I have been removed them they created when I tried to add Setting Activity, but I removed them try to pull repo.

**Comment by Abdulkadir98** [comment]
Alright, should I delete the files and create another Activity from scratch?

**Comment by MahmoudMabrok** [comment]
yes, but There is Setting Fragment is good in linking options with shared preferences.
it seems a good one to be added in-app.

**Comment by Abdulkadir98** [comment]
Yes, I know about Preference Fragment, I intend to use that. After resolving RxFirebase dependency issues , I ran the app but it's crashing. The message is:
04-26 20:44:54.913 2448-2448/education.mahmoud.quranyapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: education.mahmoud.quranyapp, PID: 2448
    java.lang.RuntimeException: Unable to start activity ComponentInfo{education.mahmoud.quranyapp/education.mahmoud.quranyapp.feature.home_Activity.Home}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process education.mahmoud.quranyapp. Make sure to call FirebaseApp.initializeApp(Context) first.

**Comment by MahmoudMabrok** [comment]
it may be caused because the project does not have a googleservice.gson file you can make a firebase project and use app package and download file then move it to the app folder.

**Comment by MahmoudMabrok** [comment]
what news with you?

**Comment by Abdulkadir98** [comment]
Hello, I'm sorry for replying late. I am caught up with some other stuff, I think you should let someone else who's interested take over. Cheers :)

**Comment by MahmoudMabrok** [comment]
Allah With you bro.

**Comment by MahmoudMabrok** [comment]
issue is solved.
