### ISSUE TITLE
V3.0 alpha crashing on my device. One plus X. Android 6.0.1

### ISSUE THREAD

**Issue by goodmuslim** [MahmoudMabrok/QuranyApp#63]
Crashing on startup.

**Comment by MahmoudMabrok** [comment]
Thanks for your contributions, and I am sorry for being late and for  this crash
i will fix it. @goodmuslim

**Comment by MahmoudMabrok** [comment]
please attach the report of a crash if it is possible.

**Comment by MahmoudMabrok** [comment]
I will close issue now, when release a new version will share so we can check if crash exists or not. 

thanks for your efforts.
